kind: pipeline
type: docker
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.5.4
    environment:
      CROSS: "1"
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - push
        - pull_request
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: cnrancher/watcher
      tag: "${DRONE_TAG}"
    when:
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

node:
  instance: agent-amd64
